# Project: Projet1
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = Benchmark.o Solution.o main.o MyAlgorithm.o Problem.o SetUpParams.o
LINKOBJ  = Benchmark.o Solution.o main.o MyAlgorithm.o Problem.o SetUpParams.o
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib" -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = "Artificial Bee Colony.exe"
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

Benchmark.o: Benchmark.cpp
	$(CPP) -c Benchmark.cpp -o Benchmark.o $(CXXFLAGS)

Solution.o: Solution.cpp
	$(CPP) -c Solution.cpp -o Solution.o $(CXXFLAGS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

MyAlgorithm.o: MyAlgorithm.cpp
	$(CPP) -c MyAlgorithm.cpp -o MyAlgorithm.o $(CXXFLAGS)

Problem.o: Problem.cpp
	$(CPP) -c Problem.cpp -o Problem.o $(CXXFLAGS)

SetUpParams.o: SetUpParams.cpp
	$(CPP) -c SetUpParams.cpp -o SetUpParams.o $(CXXFLAGS)
